# Generated by Django 3.0.6 on 2023-06-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.ImageField(null=True, upload_to='imagesProducts/'),
        ),
    ]
